version: '3'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  casdoor:
    image: casbin/casdoor:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      driverName: postgres
      dataSourceName: "user=user password=pass host=db port=5432 sslmode=disable dbname=dbname"
      origin: "https://auth.neirosetim.ru"
    depends_on:
      - db
    networks:
      - app_network

  app:
    build: .
    restart: always
    ports:
      - "8081:8081"
    environment:
      # --- База данных ---
      - DB_URL=postgresql://user:pass@db:5432/dbname
      
      # --- Основные настройки ---
      - SITE_URL=${SITE_URL}
      - AUTH_URL=${AUTH_URL}
      - CASDOOR_CERT_FILE=${CASDOOR_CERT_FILE}

      # --- Casdoor API (для синхронизации юзеров) ---
      - CASDOOR_CLIENT_ID=${CASDOOR_CLIENT_ID}
      - CASDOOR_CLIENT_SECRET=${CASDOOR_CLIENT_SECRET}

      # --- Ключи для Прямого Моста (Direct Bridge) ---
      # ВКонтакте
      - VK_CLIENT_ID=${VK_CLIENT_ID}
      - VK_CLIENT_SECRET=${VK_CLIENT_SECRET}
      
      # Google
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      
      # Яндекс
      - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
      - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}

    depends_on:
      - db
      - casdoor
    volumes:
      - ./cert.pem:/app/cert.pem
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data: