version: '3'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      # ВОЗВРАЩАЕМ СТАРЫЕ ДАННЫЕ (чтобы база пустила)
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: casdoor_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  casdoor:
    image: casbin/casdoor:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      driverName: postgres
      # Подключаемся к базе как postgres (старый юзер)
      dataSourceName: "user=postgres password=secret_password host=db port=5432 sslmode=disable dbname=casdoor_db"
      origin: "https://auth.neirosetim.ru"
    depends_on:
      - db
    networks:
      - app_network

  app:
    build: .
    restart: always
    ports:
      - "8081:8081"
    environment:
      # Подключаемся к базе как postgres
      - DB_URL=postgresql://postgres:secret_password@db:5432/casdoor_db
      
      - SITE_URL=${SITE_URL}
      - AUTH_URL=${AUTH_URL}
      - CASDOOR_CERT_FILE=${CASDOOR_CERT_FILE}
      
      # Переменные из .env (ключи)
      - CASDOOR_CLIENT_ID=${CASDOOR_CLIENT_ID}
      - CASDOOR_CLIENT_SECRET=${CASDOOR_CLIENT_SECRET}
      
      - VK_CLIENT_ID=${VK_CLIENT_ID}
      - VK_CLIENT_SECRET=${VK_CLIENT_SECRET}
      
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      
      - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
      - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}
    depends_on:
      - db
      - casdoor
    volumes:
      - ./cert.pem:/app/cert.pem
    networks:
      - app_network

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
      - casdoor
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
  caddy_data:
  caddy_config: